services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - default  
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=topicsloop.settings
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sarbinowska4444
      POSTGRES_DB: topicsloop_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: topicsloop_frontend
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true 

  frontend-dev:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"  

volumes:
  postgres_data:
  
networks:
  default:
    driver: bridge