# Generated by Django 5.2.6 on 2025-09-20 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.PositiveIntegerField(default=0, help_text='Category level: 0=main category, 1=subcategory, etc.'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category (null for main categories)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='blog.category'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'level'], name='blog_catego_parent__08ef34_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['level'], name='blog_catego_level_89b19b_idx'),
        ),
    ]
